// <auto-generated />
using BlogApi.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace BlogApi.Migrations
{
    [DbContext(typeof(BlogPostContext))]
    [Migration("20210519114859_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.6");

            modelBuilder.Entity("BlogApi.DTOs.BlogPost", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Descrition 1",
                            Title = "Test 1"
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Descrition 2",
                            Title = "Test 2"
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Descrition 3",
                            Title = "Test 3"
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Descrition 4",
                            Title = "Test 4"
                        },
                        new
                        {
                            Id = 5L,
                            Description = "Descrition 5",
                            Title = "Test 5"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
